name: Deploy workflow
run-name: Deploying application
on:
  push:
    branches:
      - main

jobs:
    build:        
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              name: Checkout project
            - uses: actions/setup-java@v3
              name: Setup Java
              with:
                distribution: 'temurin'
                java-version: 17
            - name: Run test and building
              run: ./gradlew clean test compileJava bootWar
            - name: Moving war 
              run: mkdir staging && cp target/*.war staging
            - name: Upload archive
              uses: actions/upload-artifact@v3
              with:
                name: Package
                path: staging

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v3
              name: Checkout project
            - name: Download archive
              uses: actions/download-artifact@v3
              with:
                path: staging
            - name: Display folder
              run: ls -R
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1
        
            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1
        
            - name: Build, tag, and push image to Amazon ECR
              env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                ECR_REPOSITORY: docker_nodejs_demo
                IMAGE_TAG: nodejs_demo_image
              run: |
                docker build -t 420455272363.dkr.ecr.us-east-1.amazonaws.com/hackaton-ecr:VideoTraining .
                docker push 420455272363.dkr.ecr.us-east-1.amazonaws.com/hackaton-ecr:VideoTraining
            

